= Index

// END-OF-HEADER. DO NOT MODIFY OR DELETE THIS LINE


++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="TODO.html">
                            <span class="uk-link-heading">TODO</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_20251220.html">20</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_Blog.html">Blog</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_feature.html">feature</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_things_to_do">Things to do</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_things_to_do">Things to do</h2>
<div id="kb-section-body" class="uk-container">
<div class="ulist">
<ul>
<li>
<p><del>Integrate KB4IT functionality (properties)</del></p>
</li>
<li>
<p>Allow Datatable searches</p>
</li>
<li>
<p>Allow Datable columns sorting</p>
</li>
<li>
<p><del>Use cards?</del></p>
</li>
<li>
<p><del>Same style for index post and single post</del></p>
</li>
<li>
<p>Investigate how to use github issues to build a comment system</p>
</li>
</ul>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++

++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="FIXME.html">
                            <span class="uk-link-heading">FIXME</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_20251214.html">14</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_Blog.html">Blog</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_url.html">url</a>,
                                    <a href="Tag_edit.html">edit</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_to_be_fixed">To be fixed</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_to_be_fixed">To be fixed</h2>
<div id="kb-section-body" class="uk-container">
<div class="ulist">
<ul>
<li>
<p>Topics or tage name containting spaces do not get the proper link</p>
</li>
<li>
<p>System pages shouldn&#8217;t have the edit button</p>
</li>
<li>
<p>No metadata in posts pages</p>
</li>
<li>
<p>Pass post metadata to builder? How?</p>
</li>
<li>
<p>'About this app' adoc file missing for theme blog</p>
</li>
</ul>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++

++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="20251214-0030.html">
                            <span class="uk-link-heading">Pixi: Managing Python Environments</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_20251214.html">14</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_Python.html">Python</a>,
                                    <a href="Topic_KB4IT.html">KB4IT</a>,
                                    <a href="Topic_Pixi.html">Pixi</a>,
                                    <a href="Topic_Pypi.html">Pypi</a>,
                                    <a href="Topic_Package management.html">Package management</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_project.html">project</a>,
                                    <a href="Tag_build.html">build</a>,
                                    <a href="Tag_dependency.html">dependency</a>,
                                    <a href="Tag_environment.html">environment</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_introduction">Introduction</a></li>
<li><a class="" target="" href="#_notes">Notes</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_introduction">Introduction</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p><a class="" target="" href="https://pixi.sh/latest/">Pixi</a> is a fast, modern, and reproducible package management tool for developers of all backgrounds.</p>
</div>
</div>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_notes">Notes</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p><code>pyproject.toml</code> adapted and it is on testing phase:</p>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlight"><code>[project]
authors = [{name = "Tom&#225;s V&#237;rseda", email = "tomasvirseda@gmail.com"}]
dependencies = []
name = "KB4IT"
requires-python = "&gt;= 3.12"
version = "0.7.20+build.18"
license = "GPL-3.0-or-later"
keywords = ["static-site-generator", "asciidoctor", "documentation"]
classifiers = [
 "Development Status :: 4 - Beta",
 "Environment :: Console",
 "Environment :: Web Environment",
 "Intended Audience :: Developers",
 "Intended Audience :: Information Technology",
 "Intended Audience :: System Administrators",
 "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
 "Natural Language :: English",
 "Operating System :: POSIX :: Linux",
 "Programming Language :: Python :: 3",
 "Topic :: Documentation",
 "Topic :: Software Development :: Documentation",
 "Topic :: Utilities",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
kb4it = { path = ".", editable = true }

[tool.pixi.dependencies]
mako = "&gt;=1.3.10,&lt;2"
lxml = "&gt;=6.0.2,&lt;7"

[tool.pixi.tasks]
version = "kb4it --version"
myblog_force = "kb4it -L DEBUG build /home/t00m/tmp/myblog/config/repo.json -f"
myblog = "kb4it -L DEBUG build /home/t00m/tmp/myblog/config/repo.json"</code></pre>
</div>
</div>
<div class="paragraph">
<p>Useful commands:</p>
</div>
<div class="ulist">
<ul>
<li>
<p><code>pixi install</code>: Install an environment, both updating the <code>pixi.lock</code> file and installing the environment</p>
</li>
<li>
<p><code>pixi list</code>: List the packages of the current workspace</p>
</li>
<li>
<p><code>pixi run {task name}</code>: Runs task name in the pixi environment</p>
</li>
</ul>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++

++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="20251208-2230.html">
                            <span class="uk-link-heading">Blog theme features a new index page</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_2025128.html">8</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_KB4IT.html">KB4IT</a>,
                                    <a href="Topic_Mako.html">Mako</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_index.html">index</a>,
                                    <a href="Tag_page.html">page</a>,
                                    <a href="Tag_template.html">template</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_introduction">Introduction</a></li>
<li><a class="" target="" href="#_notes">Notes</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_introduction">Introduction</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>Finally, the index page for the blog theme, is working.
Posts' headers look nice.</p>
</div>
<div class="paragraph">
<p>However, at this point, the whole code is&#8230;&#8203; spaguetti code.
<code>KB4IT</code> needs a big overhaul.</p>
</div>
</div>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_notes">Notes</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>Builder module works fine when the source files (.adoc files) are analyzed first.
But other pages, like the index page, which are build at the end, do not follow the standard process.</p>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++
