= Index

// END-OF-HEADER. DO NOT MODIFY OR DELETE THIS LINE


++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="20251231-1400-log_module.html">
                            <span class="uk-link-heading">A nice log module for KB4IT</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_20251231.html">31</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_Development.html">Development</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_logging.html">logging</a>,
                                    <a href="Tag_redirect.html">redirect</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_logic">Logic</a></li>
<li><a class="" target="" href="#_code">Code</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_logic">Logic</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>Why this module is important for KB4IT.</p>
</div>
</div>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_code">Code</h2>
<div id="kb-section-body" class="uk-container">
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code class="language-python hljs" data-lang="python">#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Log module.
File: mod_log.py
Author: Tom&#225;s V&#237;rseda
License: GPL v3
"""

import logging
from kb4it.core.env import ENV

_PATTERN = (
    "%(levelname)10s | %(lineno)4d | %(name)-20s | "
    "%(asctime)s.%(msecs)03d | %(message)s"
)

_DATEFMT = "%d/%m/%Y %H:%M:%S"


def setup_logging(
    level: str = "INFO",
    logfile: str | None = None,
):
    """
    Configure root logger once.
    """

    if level is not None:
        level_dict = {
            'DEBUG': logging.DEBUG,
            'INFO': logging.INFO,
            'WARNING': logging.WARNING,
            'ERROR': logging.ERROR,
            'CRITICAL': logging.CRITICAL
        }
        severity = level_dict.get(level, logging.DEBUG)
    else:
        severity = logging.INFO

    root = logging.getLogger()
    root.setLevel(logging.DEBUG)
    # ~ root.setLevel(getattr(logging, level.upper(), severity))

    if root.handlers:
        return  # Already configured

    formatter = logging.Formatter(_PATTERN, datefmt=_DATEFMT)

    # Console handler
    console = logging.StreamHandler()
    console.setFormatter(formatter)
    console.setLevel(severity)
    root.addHandler(console)

    # File handler
    logfile = logfile or ENV["FILE"]["LOG"]
    file_handler = logging.FileHandler(logfile, mode="w")
    file_handler.setFormatter(formatter)
    root.addHandler(file_handler)


def get_logger(name: str) -&gt; logging.Logger:
    """
    Return a named logger.
    """
    return logging.getLogger(name)


def redirect_logs(logfile: str):
    """
    Redirect file logging to a new file at runtime.
    """
    root = logging.getLogger()

    formatter = logging.Formatter(_PATTERN, datefmt=_DATEFMT)

    # Remove only existing FileHandlers
    for handler in root.handlers[:]:
        if isinstance(handler, logging.FileHandler):
            handler.flush()
            handler.close()
            root.removeHandler(handler)

    # Add new file handler
    file_handler = logging.FileHandler(logfile, mode="a")
    file_handler.setFormatter(formatter)
    file_handler.setLevel(logging.DEBUG)
    root.addHandler(file_handler)</code></pre>
</div>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++

++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="20251228-KB4IT-incremental-compiling.html">
                            <span class="uk-link-heading">KB4IT incremental compiling doesn't work (yet) in Github</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_20251228.html">28</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_Development.html">Development</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_incremental.html">incremental</a>,
                                    <a href="Tag_compiling.html">compiling</a>,
                                    <a href="Tag_vm.html">vm</a>,
                                    <a href="Tag_workflow.html">workflow</a>,
                                    <a href="Tag_cache.html">cache</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_introduction">Introduction</a></li>
<li><a class="" target="" href="#_github_actions">Github actions</a></li>
<li><a class="" target="" href="#_solution">Solution</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_introduction">Introduction</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>These days, after several fixes, I was able to produce a reliable incremental compiling of my knowledge base repositories (or force a whole compilation of the whole KB, if the app meets some conditions).</p>
</div>
<div class="paragraph">
<p>To my initial surprise, it didn&#8217;t work in Github.</p>
</div>
</div>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_github_actions">Github actions</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>In Github, when a new update is detected in the source directory, the Github action in charge (<a class="" target="" href="https://github.com/t00m/blog/blob/main/.github/workflows/update-blog.yml">update-blog.yml</a>) of updating the website is executed.</p>
</div>
<div class="paragraph">
<p>GitHub Actions runners are ephemeral. Every workflow run starts on a fresh VM, so anything written to disk is lost unless you explicitly persist it somewhere.</p>
</div>
</div>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_solution">Solution</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>To be continued&#8230;&#8203;</p>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++

++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="20251226-PyGTK4.html">
                            <span class="uk-link-heading">App development with GTK, Python and Libadwaita</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_20251228.html">28</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_Development.html">Development</a>,
                                    <a href="Topic_Documentation.html">Documentation</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_api.html">api</a>,
                                    <a href="Tag_documentation.html">documentation</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_introduction">Introduction</a></li>
<li><a class="" target="" href="#_gtk">GTK</a></li>
<li><a class="" target="" href="#_pygobject">PyGObject</a></li>
<li><a class="" target="" href="#_libadwaita">Libadwaita</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_introduction">Introduction</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>Pointers to official documentation and other useful resources.</p>
</div>
</div>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_gtk">GTK</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>Complete set of UI elements, GTK is suitable for projects ranging from small one-off tools to complete application suites.</p>
</div>
<div class="paragraph">
<p>GTK is written using the C programming language, but its also available to various programming languages through language bindings</p>
</div>
<div class="paragraph">
<p>Links:</p>
</div>
<div class="ulist">
<ul>
<li>
<p><a class="" target="" href="https://www.gtk.org/docs/">GTK Documentation</a></p>
</li>
</ul>
</div>
</div>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_pygobject">PyGObject</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>PyGObject is a Python package which provides bindings for GObject based libraries such as GTK, GStreamer, WebKitGTK, GLib, GIO and many more.</p>
</div>
<div class="paragraph">
<p>Links:</p>
</div>
<div class="ulist">
<ul>
<li>
<p><a class="" target="" href="https://pygobject.gnome.org/index.html">PyGObject</a></p>
</li>
<li>
<p><a class="" target="" href="https://api.pygobject.gnome.org/">GNOME Python API documentation</a>: This site contains documentation for the latest release of the GNOME libraries: GTK 4, LibAdwaita, etc.</p>
</li>
</ul>
</div>
</div>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_libadwaita">Libadwaita</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>Adwaita offers application developers many widgets and objects to build GNOME applications scaling from desktop workstations to mobile phones.</p>
</div>
<div class="paragraph">
<p>Links:</p>
</div>
<div class="ulist">
<ul>
<li>
<p><a class="" target="" href="https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/">Latest 1.x stable version</a></p>
</li>
</ul>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++

++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="TODO.html">
                            <span class="uk-link-heading">TODO</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_20251220.html">20</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_Blog.html">Blog</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_feature.html">feature</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_things_to_do">Things to do</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_things_to_do">Things to do</h2>
<div id="kb-section-body" class="uk-container">
<div class="ulist">
<ul>
<li>
<p><del>Integrate KB4IT functionality (properties)</del></p>
</li>
<li>
<p>Allow Datatable searches</p>
</li>
<li>
<p>Allow Datable columns sorting</p>
</li>
<li>
<p><del>Use cards?</del></p>
</li>
<li>
<p><del>Same style for index post and single post</del></p>
</li>
<li>
<p>Investigate how to use github issues to build a comment system</p>
</li>
<li>
<p><del>Display properties in right menu</del></p>
</li>
<li>
<p><del>Display link for editing a post</del></p>
</li>
<li>
<p><del>Display entry for events</del></p>
</li>
</ul>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++

++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="FIXME.html">
                            <span class="uk-link-heading">FIXME</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_20251214.html">14</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_Blog.html">Blog</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_url.html">url</a>,
                                    <a href="Tag_edit.html">edit</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_to_be_fixed">To be fixed</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_to_be_fixed">To be fixed</h2>
<div id="kb-section-body" class="uk-container">
<div class="ulist">
<ul>
<li>
<p><del>Topics or tage name containting spaces do not get the proper link</del></p>
</li>
<li>
<p><del>System pages shouldn't have the edit button</del></p>
</li>
<li>
<p>No metadata in posts pages</p>
</li>
<li>
<p><del>Pass post metadata to builder? How?</del>: build_page can receive a new theme var</p>
</li>
<li>
<p>'About this app' adoc file missing for theme blog</p>
</li>
<li>
<p><del>Integrate KB4IT functionality (properties)</del></p>
</li>
<li>
<p><del>Display the right page title in browser</del></p>
</li>
</ul>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++

++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="20251214-0030.html">
                            <span class="uk-link-heading">Pixi: Managing Python Environments</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_20251214.html">14</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_Package_management.html">Package management</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_project.html">project</a>,
                                    <a href="Tag_build.html">build</a>,
                                    <a href="Tag_dependency.html">dependency</a>,
                                    <a href="Tag_environment.html">environment</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_introduction">Introduction</a></li>
<li><a class="" target="" href="#_notes">Notes</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_introduction">Introduction</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p><a class="" target="" href="https://pixi.sh/latest/">Pixi</a> is a fast, modern, and reproducible package management tool for developers of all backgrounds.</p>
</div>
</div>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_notes">Notes</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p><code>pyproject.toml</code> adapted and it is on testing phase:</p>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code class="language-none hljs">[project]
authors = [{name = "Tom&#225;s V&#237;rseda", email = "tomasvirseda@gmail.com"}]
dependencies = []
name = "KB4IT"
requires-python = "&gt;= 3.12"
version = "0.7.20+build.18"
license = "GPL-3.0-or-later"
keywords = ["static-site-generator", "asciidoctor", "documentation"]
classifiers = [
 "Development Status :: 4 - Beta",
 "Environment :: Console",
 "Environment :: Web Environment",
 "Intended Audience :: Developers",
 "Intended Audience :: Information Technology",
 "Intended Audience :: System Administrators",
 "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
 "Natural Language :: English",
 "Operating System :: POSIX :: Linux",
 "Programming Language :: Python :: 3",
 "Topic :: Documentation",
 "Topic :: Software Development :: Documentation",
 "Topic :: Utilities",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
kb4it = { path = ".", editable = true }

[tool.pixi.dependencies]
mako = "&gt;=1.3.10,&lt;2"
lxml = "&gt;=6.0.2,&lt;7"

[tool.pixi.tasks]
version = "kb4it --version"
myblog_force = "kb4it -L DEBUG build /home/t00m/tmp/myblog/config/repo.json -f"
myblog = "kb4it -L DEBUG build /home/t00m/tmp/myblog/config/repo.json"</code></pre>
</div>
</div>
<div class="paragraph">
<p>Useful commands:</p>
</div>
<div class="ulist">
<ul>
<li>
<p><code>pixi install</code>: Install an environment, both updating the <code>pixi.lock</code> file and installing the environment</p>
</li>
<li>
<p><code>pixi list</code>: List the packages of the current workspace</p>
</li>
<li>
<p><code>pixi run {task name}</code>: Runs task name in the pixi environment</p>
</li>
</ul>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++

++++
<!-- Template POST_ADOC_INDEX.tpl :: START -->
<!-- Blog Post :: START -->
<div class="uk-card uk-card-small uk-card-body post-card">
    <div class="uk-container uk-container-small">

        <!-- Header -->
        <header class="uk-margin-small-bottom uk-background-muted">
            <div class="uk-flex uk-flex-middle uk-margin-bottom">
                <div class="uk-width">
                    <h5 class="uk-card-title uk-margin-remove uk-text-center">
                        <a class="uk-link-toggle" href="20251208-2230.html">
                            <span class="uk-link-heading">Blog theme features a new index page</span>
                        </a>
                    </h5>
                    <div class="uk-width">
                        <ul class="uk-subnav uk-subnav-divider uk-margin-small-top uk-flex-center uk-text-meta">
                            <li>
                                <span uk-icon="user"></span>
                                <span class="uk-margin-small-left"><a href="Author_Tomás_Vírseda.html">Tomás Vírseda</a></span>
                            </li>
                            <li>
                                <span uk-icon="calendar"></span>
                                <span class="uk-margin-small-left"><a href="events_2025128.html">8</a>/<a href="events_202512.html">12</a>/<a href="events_2025.html">2025</a></span>
                            </li>
                            <li>
                                <span uk-icon="star"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Topic_Development.html">Development</a>
                                </span>
                            </li>
                            <li>
                                <span uk-icon="tag"></span>
                                <span class="uk-margin-small-left">
                                    <a href="Tag_index.html">index</a>,
                                    <a href="Tag_page.html">page</a>,
                                    <a href="Tag_template.html">template</a>
                                </span>
                            </li>
                        </ul>
                    </div>
                    <!-- Tags and Topics -->
                </div>
            </div>
            <hr>
        </header>

        <!-- Body -->
        <article class="uk-article">
            <div hidden>
<div id="toctitle">Table of Contents</div>
<ul class="sectlevel1">
<li><a class="" target="" href="#_introduction">Introduction</a></li>
<li><a class="" target="" href="#_notes">Notes</a></li>
</ul>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_introduction">Introduction</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>Finally, the index page for the blog theme, is working.
Posts' headers look nice.</p>
</div>
<div class="paragraph">
<p>However, at this point, the whole code is&#8230;&#8203; spaguetti code.
<code>KB4IT</code> needs a big overhaul.</p>
</div>
</div>
</div>
<div id="kb-sect1" class="uk-margin-small-bottom uk-card uk-card-small uk-card-body uk-card-hover uk-border-rounded">

<h2 class="uk-card-title" id="_notes">Notes</h2>
<div id="kb-section-body" class="uk-container">
<div class="paragraph">
<p>Builder module works fine when the source files (.adoc files) are analyzed first.
But other pages, like the index page, which are build at the end, do not follow the standard process.</p>
</div>
</div>
</div>
        </article>

        <!-- Footer -->
        <footer class="uk-margin-small-top uk-text-muted">
            <hr>
            <div class="uk-flex uk-flex-between uk-flex-middle">
            </div>
        </footer>
    </div>
</div>
<p></p>
<!-- Template POST_ADOC_INDEX.tpl :: END -->
++++
