= App development with GTK, Python and Libadwaita
:Author:                Tomás Vírseda
:Category:              Post, Bookmark
:Topic:                 Development, Documentation
:Product:               GTK, Libadwaita, PyGObject, GNOME, MiAZ
:Tag:                   api, documentation
:Programming Language:  Python
:Updated:               2025-12-28 18:40:00

// END-OF-HEADER. DO NOT MODIFY OR DELETE THIS LINE

== Introduction

Pointers to official documentation and other useful resources.

== GTK

Complete set of UI elements, GTK is suitable for projects ranging from small one-off tools to complete application suites. 

GTK is written using the C programming language, but its also available to various programming languages through language bindings

Links:

* https://www.gtk.org/docs/[GTK Documentation]

== PyGObject

PyGObject is a Python package which provides bindings for GObject based libraries such as GTK, GStreamer, WebKitGTK, GLib, GIO and many more.

Links:

* https://pygobject.gnome.org/index.html[PyGObject]
* https://api.pygobject.gnome.org/[GNOME Python API documentation]: This site contains documentation for the latest release of the GNOME libraries: GTK 4, LibAdwaita, etc. 

== Libadwaita

Adwaita offers application developers many widgets and objects to build GNOME applications scaling from desktop workstations to mobile phones. 

Links:

* https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/[Latest 1.x stable version]
